package net.a.g.jbpm.pattern.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Person extends org.drools.persistence.jpa.marshaller.VariableEntity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "PERSON_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "PERSON_ID_SEQ", name = "PERSON_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("Email")
	private java.lang.String email;

	@org.kie.api.definition.type.Label("Country")
	private java.lang.String country;

	@org.kie.api.definition.type.Label("Date of Birth")
	private java.time.LocalDate birthDate;

	public Person() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.time.LocalDate getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(java.time.LocalDate birthDate) {
		this.birthDate = birthDate;
	}

	public Person(java.lang.Long id, java.lang.String name,
			java.lang.String email, java.lang.String country,
			java.time.LocalDate birthDate) {
		this.id = id;
		this.name = name;
		this.email = email;
		this.country = country;
		this.birthDate = birthDate;
	}

	@Override
	public String toString() {
		return "{ id = "+id+ 
		", name = "+name+
		", email = "+email+
		", country = "+country+
		", birthDate = "+birthDate+"}";
	}

}